"""
CASTEP Cell Keywords
"""
from pygments.lexer import words

CELL = {
    "block": ("LATTICE_CART", "LATTICE_ABC", "POSITIONS_FRAC", "POSITIONS_ABS", "SYMMETRY_OPS",
              "IONIC_CONSTRAINTS", "CELL_CONSTRAINTS", "EXTERNAL_PRESSURE", "SPECIES_MASS",
              "SPECIES_POT", "IONIC_VELOCITIES", "SPECIES_LCAO_STATES", "KPOINTS_LIST",
              "KPOINT_LIST", "BS_KPOINT_PATH", "BS_KPOINT_LIST", "BS_KPOINTS_PATH",
              "BS_KPOINTS_LIST", "PHONON_SUPERCELL_MATRIX", "PHONON_KPOINT_PATH",
              "PHONON_KPOINT_LIST", "PHONON_GAMMA_DIRECTIONS", "PHONON_KPOINTS_PATH",
              "PHONON_KPOINTS_LIST", "PHONON_FINE_KPOINT_LIST", "PHONON_FINE_KPOINT_PATH",
              "OPTICS_KPOINTS_LIST", "OPTICS_KPOINT_LIST", "MAGRES_KPOINT_LIST",
              "MAGRES_KPOINT_PATH", "POSITIONS_FRAC_PRODUCT", "POSITIONS_ABS_PRODUCT",
              "POSITIONS_FRAC_INTERMEDIATE", "POSITIONS_ABS_INTERMEDIATE", "SPECIES_GAMMA",
              "SPECIES_Q", "SUPERCELL_KPOINTS_LIST", "SUPERCELL_KPOINT_LIST", "SUPERCELL_MATRIX",
              "NONLINEAR_CONSTRAINTS", "EXTERNAL_EFIELD", "HUBBARD_U", "HUBBARD_ALPHA",
              "CHEMICAL_POTENTIAL", "ELNES_KPOINT_LIST", "SPECTRAL_KPOINT_PATH",
              "SPECTRAL_KPOINT_LIST", "SPECTRAL_KPOINTS_PATH", "SPECTRAL_KPOINTS_LIST",
              "SEDC_CUSTOM_PARAMS", "CELL_DEVEL_CODE", "EXTERNAL_BFIELD", "EP_KPOINT_PAIRS"),

    "defined": ("SYMMETRY_GENERATE", "ATOMIC_INIT", "SNAP_TO_SYMMETRY"),

    "physical": ("SYMMETRY_TOL", "KPOINTS_MP_SPACING", "KPOINT_MP_SPACING",
                 "BS_KPOINT_PATH_SPACING", "BS_KPOINT_MP_SPACING", "BS_KPOINTS_PATH_SPACING",
                 "BS_KPOINTS_MP_SPACING", "PHONON_KPOINT_PATH_SPACING", "PHONON_KPOINT_MP_SPACING",
                 "PHONON_KPOINTS_PATH_SPACING", "PHONON_FINE_KPOINT_PATH_SPACING",
                 "PHONON_FINE_KPOINT_MP_SPACING", "OPTICS_KPOINTS_MP_SPACING",
                 "OPTICS_KPOINT_MP_SPACING", "MAGRES_KPOINT_PATH_SPACING",
                 "MAGRES_KPOINT_MP_SPACING", "SUPERCELL_KPOINTS_MP_SPACING",
                 "SUPERCELL_KPOINT_MP_SPACING", "POSITIONS_NOISE", "CELL_NOISE",
                 "ELNES_KPOINT_MP_SPACING", "SPECTRAL_KPOINT_PATH_SPACING",
                 "SPECTRAL_KPOINT_MP_SPACING", "SPECTRAL_KPOINTS_PATH_SPACING",
                 "SPECTRAL_KPOINTS_MP_SPACING"),

    "boolean": ("FIX_COM", "FIX_ALL_IONS", "FIX_ALL_CELL", "FIX_VOL"),

    "int": ("KPOINTS_MP_GRID", "KPOINT_MP_GRID", "BS_KPOINT_MP_GRID", "BS_KPOINTS_MP_GRID",
            "PHONON_KPOINT_MP_GRID", "PHONON_FINE_KPOINT_MP_GRID", "OPTICS_KPOINTS_MP_GRID",
            "OPTICS_KPOINT_MP_GRID", "MAGRES_KPOINT_MP_GRID", "SUPERCELL_KPOINTS_MP_GRID",
            "SUPERCELL_KPOINT_MP_GRID", "ELNES_KPOINT_MP_GRID", "SPECTRAL_KPOINT_MP_GRID",
            "SPECTRAL_KPOINTS_MP_GRID"),

    "string": ("KPOINTS_MP_OFFSET", "KPOINT_MP_OFFSET", "BS_KPOINT_MP_OFFSET",
               "BS_KPOINTS_MP_OFFSET", "PHONON_KPOINT_MP_OFFSET", "PHONON_FINE_KPOINT_MP_OFFSET",
               "OPTICS_KPOINTS_MP_OFFSET", "OPTICS_KPOINT_MP_OFFSET", "MAGRES_KPOINT_MP_OFFSET",
               "SUPERCELL_KPOINTS_MP_OFFSET", "SUPERCELL_KPOINT_MP_OFFSET", "JCOUPLING_SITE",
               "ELNES_KPOINT_MP_OFFSET", "SPECTRAL_KPOINT_MP_OFFSET", "SPECTRAL_KPOINTS_MP_OFFSET",
               "UNIT_CELL"),

    "real": ("QUANTISATION_AXIS", "QUANTIZATION_AXIS"),
}
# Map words to REs
CELL = {key: words(val, prefix=r"\b", suffix=r"\b").get() for key, val in CELL.items()}
